docker:
  image: yegor256/rultor-image:1.21.0
assets:
  docker-password: yegor256/home#assets/docker-password
install: |
  pdd --file=/dev/null
merge:
  script: |
    sudo make install
    make REPO=yegor256/tojos
    make validate REPO=yegor256/tojos
release:
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit 1
    sed -i "s/0\.0\.0/${tag}/g" Makefile
    repo=yegor256/cam
    sudo docker build --no-cache --tag "${repo}:${tag}" "$(pwd)"
    mkdir /tmp/dataset
    sudo docker run --rm -v /tmp/dataset:/dataset -e "REPO=yegor256/tojos" -e "TARGET=/dataset" "${repo}:${tag}" 'make -e'
    cat ../docker-password | sudo docker login --password-stdin --username yegor256
    sudo docker push "${repo}:${tag}"
