---
name: latexmk
'on':
  push:
  pull_request:
concurrency:
  group: latexmk-${{ github.ref }}
  cancel-in-progress: true
jobs:
  latexmk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - uses: yegor256/latexmk-action@0.11.1
        with:
          opts: -pdf
          path: paper
          depends: DEPENDS.txt
