---
name: make
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: make-${{ github.ref }}
  cancel-in-progress: true
jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: yegor256/cam@master