---
name: make
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yegor256/cam@master
