---
name: make
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: make-${{ github.ref }}
  cancel-in-progress: true
jobs:
  make:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: yegor256/cam@master