---
name: make
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: make-${{ github.ref }}
  cancel-in-progress: true
jobs:
  make:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: yegor256/cam@master