---
name: make
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: make-${{ github.ref }}
  cancel-in-progress: true
jobs:
  make:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - run: docker build . -t cam
      - run: docker run --rm cam make install env lint test
