name: Check Python code

on:
  pull_request:
    branches:
      - master

jobs:
  type_hints:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for type hints
        run: mypy --strict .